### ISSUE TITLE
AttributeError while serving OpenAPI documentation

### ISSUE THREAD

**Issue by svidela** [marshmallow-code/flask-smorest#14]
Hi, 

First of all, thanks for such a great framework. I started using flask-rest-api only a few days ago and my API looks much better now.

I report this issue mostly for documentation purpose because I believe it's fixed with this [commit](https://github.com/Nobatek/flask-rest-api/commit/9e06e3c2e236c4b5d412a84928c4cc132802f0e2#diff-e4a0d7f4ac1c83110a42a17dc640a46c. ) but I thought it may be helpful for others until the next release of flask-rest-api.

Using flask-rest-api 0.9.0 with apispec 1.0.0b3, if you try to access the openapi.json file you will get the following error:

```
127.0.0.1 - - [10/Oct/2018 19:55:28] "GET /openapi/openapi.json HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/flask_rest_api/spec/__init__.py", line 123, in _openapi_json
    json.dumps(self.spec.to_dict(), indent=2),
  File "/Users/sancho/.local/share/virtualenvs/preciosa--GgWvvys/lib/python3.7/site-packages/apispec/core.py", line 118, in to_dict
    info.setdefault('title', self.title)
AttributeError: 'NoneType' object has no attribute 'setdefault'
```

To solve this issue, you either install flask-rest-api from github (after this [commit](https://github.com/Nobatek/flask-rest-api/commit/9e06e3c2e236c4b5d412a84928c4cc132802f0e2#diff-e4a0d7f4ac1c83110a42a17dc640a46c. )) or you must do one of these:

In your config.py,
```
API_SPEC_OPTIONS = {
    'info': {
        'title': 'API Test',
        'version': 'v1'
    }
}
```

or

```
api = Api(app, spec_kwargs={'info': {'title': 'API Test', 'version': 'v1'}})
```
or using the factory pattern
```
api = Api()
def create_app():
    app = Flask(__name__)
    ...
    api.init_app(app, spec_kwargs={'info': {'title': 'API Test', 'version': 'v1'}})
```

**Comment by lafrech** [comment]
Thank you for the positive feedback. I appreciate.

I just released 0.9.1.
