### ISSUE TITLE
Arguments on location='headers' can not parse as json the headers (tuples)

### ISSUE THREAD

**Issue by ev-agelos** [marshmallow-code/flask-smorest#179]
```
@blp.arguments(TokenSchema, location='headers')
@blp.arguments(OtherSchema, location='query')
def get(self, token, other):
    ...
```

I think it fails while trying to parse as json the headers which is a MultiDict with tuples..
I guess I could work around it by using `@pre_load` to unpack them except if I am doing something wrong here?
 
```
Traceback (most recent call last):
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/app.py", line 2112, in make_response
    rv = jsonify(rv)
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "/home/me/.local/share/virtualenvs/project/lib/python3.8/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.8/json/encoder.py", line 376, in _iterencode_dict
    raise TypeError(f'keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not tuple
```

**Comment by ev-agelos** [comment]
It is working now, I do not know what was happening before, I am closing the issue.
