### ISSUE TITLE
Concurrent requests using Apache and wsgi file leads to DuplicateComponentNameError

### ISSUE THREAD

**Issue by Finn10111** [marshmallow-code/flask-smorest#215]
Hi,

I wrote a small application which which stores and serves some simple data via API. Everything seems to be working fine until one of my systems wants to do more than one get request per time. Then The request fails with an exception like this:

```
mod_wsgi (pid=1983): Exception occurred processing WSGI script '/var/www/vhosts/powermeter/powermeter.wsgi'.
Traceback (most recent call last):
  File "/var/www/vhosts/powermeter/powermeter.wsgi", line 18, in application
    app = create_app(os.getenv('APP_CONFIG', 'production'))
  File "/var/www/vhosts/powermeter/app/__init__.py", line 26, in create_app
    api.init_app(app)
  File "/var/www/vhosts/powermeter/lib/python3.7/site-packages/flask_smorest/__init__.py", line 74, in init_app
    self._register_responses()
  File "/var/www/vhosts/powermeter/lib/python3.7/site-packages/flask_smorest/spec/__init__.py", line 259, in _register_responses
    self.spec.components.response(status.name, response)
  File "/var/www/vhosts/powermeter/lib/python3.7/site-packages/apispec/core.py", line 98, in response
    component_id
apispec.exceptions.DuplicateComponentNameError: Another response with name "PROCESSING" is already registered.
```

The exception is sometimes different and also can look like this:

```
apispec.exceptions.DuplicateComponentNameError: Another response with name "UNAUTHORIZED" is already registered.
apispec.exceptions.DuplicateComponentNameError: Another response with name "SWITCHING_PROTOCOLS" is already registered.
apispec.exceptions.DuplicateComponentNameError: Another response with name "CONTINUE" is already registered.
```

This error doesn't occur when I am doing the requests manually with curl or in the browser. I don't even know if this really is a bug or I am doing something wrong.

My `app/__init__.py` looks like this:

```
from flask import Flask
from flask_smorest import Api
from flask_marshmallow import Marshmallow
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


api = Api()
db = SQLAlchemy()
ma = Marshmallow()


def create_app(cfg='default'):
    from config import config
    app = Flask(__name__)
    app.config.from_object(config[cfg])
    app.url_map.strict_slashes = False

    config[cfg].init_app(app)
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    from . import resources

    api.init_app(app)
    db.init_app(app)
    ma.init_app(app)
    Migrate(app, db)
    resources.register_blueprints(api)

    return app
```

And based on this link I use a wsgi file with Apache: https://flask.palletsprojects.com/en/1.1.x/deploying/mod_wsgi/
```
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
activate_this = os.path.join(os.path.dirname(__file__), 'bin/activate_this.py')
with open(activate_this) as file_:
    exec(file_.read(), dict(__file__=activate_this))
from app import create_app

def application(environ, start_response):
    ENVIRONMENT_VARIABLES = [
        'APP_CONFIG',
        'APP_PRODUCTION_DATABASE_URI',
        'APP_TESTING_DATABASE_URI',
        'APP_DEVELOPMENT_DATABASE_URI'
    ]
    for key in ENVIRONMENT_VARIABLES:
        os.environ[key] = environ.get(key, '')
    app = create_app(os.getenv('APP_CONFIG', 'production'))
    return app(environ, start_response)

```

**Comment by lafrech** [comment]
This happens because the same `Api` instance runs `init_app` several times.

I believe this is because

- `api = Api()` runs at import time, out of `create_app`, so a single instance is used on each call to `create_app`
- `create_app` is called on each call to the wsgi file. I suppose when running multithreads, the wsgi file is executed several times.

Changing one of those two conditions would solve it.

The first is easy. Just instantiate Api in `create_app`. You shouldn't need the `Api` object at import time. Only the blueprints.

I don't know about the second. You seem to be using a wsgi feature I don't know about. My wsgi file instantiates a single app with this line at the end:

```py
application = create_app()
```

**Comment by Finn10111** [comment]
Oh so it was simply my fault, thanks a lot. I put Api() initialization within create_app and now I can't reproduce the error anymore.
