### ISSUE TITLE
APISpec marshmallow extension does not expect `example` passed in from blp.arguments 

### ISSUE THREAD

**Issue by technolingo** [marshmallow-code/flask-smorest#225]
As title, when passing `example` or `examples` to `blp.arguments` as documented:
```
@blp.arguments(PetQuerySchema, location='query', required=True, example={'pet_name': 'foobar'}, description='Pet query parameter')
    def get_pets():
        pass
```
It throws the following error:

```
backend_1   | Traceback (most recent call last):
backend_1   |   File "manage.py", line 9, in <module>
backend_1   |     from project.app_config import dd_configure, log_configure
backend_1   |   File "/usr/src/app/project/__init__.py", line 4, in <module>
backend_1   |     from project.views.v2 import *
backend_1   |   File "/usr/src/app/project/views/v2/__init__.py", line 1, in <module>
backend_1   |     from .pets import *
backend_1   |   File "/usr/src/app/project/views/v2/pets.py", line 95, in <module>
backend_1   |     api.register_blueprint(blp)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/flask_smorest/__init__.py", line 87, in register_blueprint
backend_1   |     blp.register_views_in_doc(self, self._app, self.spec)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/flask_smorest/blueprint.py", line 204, in register_views_in_doc
backend_1   |     spec.path(rule=rule, operations=doc, parameters=parameters)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/apispec/core.py", line 280, in path
backend_1   |     plugin.operation_helper(path=path, operations=operations, **kwargs)
backend_1   |   File "/usr/local/lib/python3.7/site-packages/apispec/ext/marshmallow/__init__.py", line 195, in operation_helper
backend_1   |     operation["parameters"]
backend_1   |   File "/usr/local/lib/python3.7/site-packages/apispec/ext/marshmallow/schema_resolver.py", line 79, in resolve_parameters
backend_1   |     schema_instance, location=parameter.pop("in"), **parameter
backend_1   | TypeError: schema2parameters() got an unexpected keyword argument 'example'
```

I'm using:
```
Flask==1.1.2
marshmallow==3.10.0
apispec==4.0.0
flask-smorest==0.28.0
```

**Comment by technolingo** [comment]
Oh, I just saw that `example` and `examples` are only supported for `json` parameters. So there's no way of passing `example` and `description` to parameters in other locations like `query`, `path`, etc.? :(

**Comment by technolingo** [comment]
Nvm, `example` and `description` can be passed in `marshmallow` schemas directly.

**Comment by lafrech** [comment]
Yes, this is the way to go.
