### ISSUE TITLE
Question: multiple @response decorators

### ISSUE THREAD

**Issue by asyncee** [marshmallow-code/flask-smorest#29]
Hello, i have defined two response types on my view function:

```
    @blp.response(code=404, description="Product not found")
    @blp.response(ProductSchema(), code=200)
    def get(self, product_id):
        ...
```

Generated documentations contains description of those two possible response types and looks perfect.

If view is aborted via `abort(404)` then everything works as expected, but i got an error otherwise:

```
2018-11-22 18:18:43.686 INFO    127.0.0.1 - - [22/Nov/2018 18:18:43] "GET /api/products/1/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/views.py", line 158, in dispatch_request
    return meth(*args, **kwargs)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask_rest_api/response.py", line 55, in wrapper
    resp = jsonify(self._prepare_response_content(result_dump))
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/json/__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/json/__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/Users/asyncee/app/env/lib/python3.6/site-packages/flask/json/__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Response' is not JSON serializable
```

So my question is: am i doing everything correctly and multiple decorators supported?

**Comment by lafrech** [comment]
Hi.

`response` is meant to be use at most once per resource.

I admit this could be clarified in the docs and more examples could help.

What it does is, given a response `Schema`

- document that response schema
- serialize data with that response schema

So you don't have to repeat yourself.

The assumption is that a view can only have one "normal" output, with one or no schema and one status code. All other outputs are errors.

Maybe this assumption is too strong. Anyway, your use case conforms to it, so that's not an issue.

What you can do right now (out of my head but I suppose it would work):

```py
    @blp.doc({'responses': {'404': {'description': 'product not found'}}})
    @blp.response(ProductSchema(), code=200)
    def get(self, product_id):
        ...
```

I'd like to provide a nicer way to pass this doc.

Latest devs in apispec 1 beta add a way to define response objects to reuse along the doc, so that you could define a complete "404 error" response, with a description of the response structure, and reference it here. We'd still need a decorator to specify alternate responses.

Following the logic that there's only one normal path, all alternative responses are errors, so we could have an `errors` decorator allowing to document possible error cases.

It would be nice to be able to define the 404 error globally, as it can occur on any resource, but the OpenAPI spec does not allow defining global responses (see https://swagger.io/docs/specification/describing-responses/). Maybe flask-rest-api could provide this: dispatch a common response on all resources.

**Comment by asyncee** [comment]
Thank you for clarification, in my experience this is usually true that one endpoint has a single normal path, so your assumption is 100% correct (for me).

I will use @blp.doc while other choices are not available.

Thanks!

**Comment by zedrdave** [comment]
Just a quick note to mention that, unless I'm missing a recent branch change, `@blueprint.doc` takes a `**kwargs`, so your example won't work and should be instead:

```
    @blp.doc(responses = {'404': {'description': 'product not found'}})
    @blp.response(ProductSchema(), code=200)
    def get(self, product_id):
        ...
```

Also: I'm not sure if that's what you have in mind (it seems maybe not), but short of having the ability to set response descriptions for all resources, it would be really nice to be able to set default responses per resource (by using the decorator at the class level).

**Comment by revmischa** [comment]
It would be nice if it was easy to document errors (e.g. 403) using multiple `@blp.response`

**Comment by erdnaxeli** [comment]
This "only one response per resource" thing should be documented, it's not really intuitive.

**Comment by BorjaEst** [comment]
What for "PUT" where 201 and 204 are valid?
See #166.
