### ISSUE TITLE
Exception after installing 0.13.1

### ISSUE THREAD

**Issue by asyncee** [marshmallow-code/flask-smorest#41]
Hello, i have just updated from version 0.12.0 and experiencing following issue:

```
127.0.0.1 - - [24/Feb/2019 12:06:49] "GET /api/endpoint HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/user/git/project/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/user/git/project/env/lib/python3.7/site-packages/flask/cli.py", line 76, in find_best_app
    app = call_factory(script_info, app_factory)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/flask/cli.py", line 116, in call_factory
    return app_factory()
  File "/Users/user/git/project/app.py", line 36, in create_app
    api.init_app(app)
  File "/Users/user/git/project/api/__init__.py", line 10, in init_app
    api.init_app(app)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/flask_rest_api/__init__.py", line 61, in init_app
    self._init_spec(**(spec_kwargs or {}))
  File "/Users/user/git/project/env/lib/python3.7/site-packages/flask_rest_api/spec/__init__.py", line 193, in _init_spec
    self.spec.components.schema(name, schema=schema_cls, **kwargs)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/apispec/core.py", line 141, in schema
    ret.update(plugin.schema_helper(name, component, **kwargs) or {})
  File "/Users/user/git/project/env/lib/python3.7/site-packages/apispec/ext/marshmallow/__init__.py", line 158, in schema_helper
    json_schema = self.openapi.schema2jsonschema(schema_instance)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 645, in schema2jsonschema
    jsonschema = self.fields2jsonschema(fields, partial=partial, ordered=ordered)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 669, in fields2jsonschema
    property = self.field2property(field_obj)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 421, in field2property
    ret["items"] = self.field2property(field.container)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 415, in field2property
    schema_dict = self.resolve_nested_schema(field.schema)
  File "/Users/user/git/project/env/lib/python3.7/site-packages/marshmallow/fields.py", line 447, in schema
    dump_only=self._nested_normalized_option('dump_only'),
TypeError: __init__() missing 1 required positional argument: 'cls_or_instance'
```

**Comment by asyncee** [comment]
Sorry, that was a problem in my code.
