### ISSUE TITLE
flask smorest import error

### ISSUE THREAD

**Issue by Tarundeep6** [marshmallow-code/flask-smorest#565]
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "C:\Users\USER\Desktop\restapi\venv\Lib\site-packages\flask\cli.py", line 219, in locate_app
    __import__(module_name)
  File "C:\Users\USER\Desktop\restapi\app.py", line 2, in <module>
    from flask_smorest import Api
  File "C:\Users\USER\Desktop\restapi\venv\Lib\site-packages\flask_smorest\__init__.py", line 6, in <module>      
    from .blueprint import Blueprint  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\restapi\venv\Lib\site-packages\flask_smorest\blueprint.py", line 43, in <module>    
    from flask.views import MethodViewType
ImportError: cannot import name 'MethodViewType' from 'flask.views' (C:\Users\USER\Desktop\restapi\venv\Lib\site-packages\flask\views.py)

how can i solve this issue 

verisons used :
Python 3.11.2
Flask 2.3.3
Werkzeug 2.3.7
Flask-smorest 0.36.0

**Comment by lafrech** [comment]
This was fixed more than one year ago in [0.39.0 (2022-08-16)](https://github.com/marshmallow-code/flask-smorest/blob/master/CHANGELOG.rst#0390-2022-08-16)...

> how can i solve this issue

    pip install -U flask-smorest
