### ISSUE TITLE
Obscure error when pagination receives bad argument

### ISSUE THREAD

**Issue by jan-golda** [marshmallow-code/flask-smorest#88]
When we are using [pagination decorator](https://flask-rest-api.readthedocs.io/en/stable/api_reference.html#flask_rest_api.Blueprint.paginate), requests can accept `page` and `page_size` query arguments.
Everythink works nice as long as these arguments are set to proper integer, like: `?page=3&page_size=10`, but when they are set to something different, like `?page=3as`, an obscure error is thrown:

```
Traceback (most recent call last):
  File "####/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "####/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "####/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "####/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "####/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "####/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "####/lib/python3.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "####/lib/python3.7/site-packages/flask/app.py", line 2111, in make_response
    rv = jsonify(rv)
  File "####/lib/python3.7/site-packages/flask/json/__init__.py", line 370, in jsonify
    dumps(data, indent=indent, separators=separators) + "\n",
  File "####/lib/python3.7/site-packages/flask/json/__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "####/lib/python3.7/site-packages/flask/json/__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PaginationParametersSchema is not JSON serializable
```
Causing `500 Internal Server Error` response.

To me it looks like pagination is not checking type of arguments before using them.
Of course I could add my own check for this, but it would be much nicer if pagination would do it by its own, resulting in for example `400 Bad Request`.

Other examples that can cause this (all of these are very likely to happen due to error by end user):
`?page=1page_size=10`
`?page=1?page_size=10`
`?page=text`

**Comment by lafrech** [comment]
That would be quite an ugly bug indeed.

I can't reproduce.

If I modify `test_pagination_parameters` to trigger this

```py
    @pytest.mark.parametrize('collection', [1000, ], indirect=True)
    def test_pagination_parameters(self, app_fixture):
        # page = 2, page_size = 5
        response = app_fixture.client.get(
            '/test/',
            query_string={'page': '2s', 'page_size': 5}  # <-- here
        )
```

I get a 422 response as expected.

**Comment by jan-golda** [comment]
Ouch, my bad. Your code indeed handles that.
After your response I checked once again in place that I fought I checked, and looks like my error handler was not prepared to receive Schema in `response.data.schema`.
I was throw off by stack trace that did not contained my code.

I am sorry for taking your time. And thanks!
